const fields = [
    {
        key:'username',
        label:'用戶名',
        formType:'text',
    },
    {
        key:'password',
        label:'密碼',
        formType:'password',
    },
    {
        key:'email',
        label:'郵箱',
    },
    {
        key:'userrole',
        label:'用戶角色',
        dataType:'picklist'
    },
    {
        key:'status',
        label:'狀態',
        dataType:'switch'
    },
    {
        key:'remark',
        label:'備注',
    }
]
export default fields